version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test 
      - run: flutter -v build apk
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
      - run: flutter -v build ios
      - store_artifacts:
          path: build/app/outputs/flutter-ios/app-release.ipa     